=== Jguer/IST-Discrete-Stochastic-Simulator/simulation.dtd
<?xml encoding="utf-8"?>

<!ELEMENT simulation (grid,initialpoint,finalpoint,specialcostzones,obstacles,events)>
<!ATTLIST simulation
    xmlns CDATA #FIXED ''
    comfortsens CDATA #REQUIRED
    finalinst CDATA #REQUIRED
    initpop CDATA #REQUIRED
    maxpop CDATA #REQUIRED>

<!ELEMENT grid EMPTY>
<!ATTLIST grid
    xmlns CDATA #FIXED ''
    colsnb CDATA #REQUIRED
    rowsnb CDATA #REQUIRED>

<!ELEMENT initialpoint EMPTY>
<!ATTLIST initialpoint
    xmlns CDATA #FIXED ''
    xinicial CDATA #REQUIRED
    yinicial CDATA #REQUIRED>

<!ELEMENT finalpoint EMPTY>
<!ATTLIST finalpoint
    xmlns CDATA #FIXED ''
    xfinal CDATA #REQUIRED
    yfinal CDATA #REQUIRED>

<!ELEMENT specialcostzones (zone)+>
<!ATTLIST specialcostzones
    xmlns CDATA #FIXED ''>

<!ELEMENT obstacles (obstacle)+>
<!ATTLIST obstacles
    xmlns CDATA #FIXED ''
    num CDATA #REQUIRED>

<!ELEMENT events (death,reproduction,move)>
<!ATTLIST events
    xmlns CDATA #FIXED ''>

<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
    xmlns CDATA #FIXED ''
    xfinal CDATA #REQUIRED
    xinicial CDATA #REQUIRED
    yfinal CDATA #REQUIRED
    yinicial CDATA #REQUIRED>

<!ELEMENT obstacle EMPTY>
<!ATTLIST obstacle
    xmlns CDATA #FIXED ''
    xpos CDATA #REQUIRED
    ypos CDATA #REQUIRED>

<!ELEMENT death EMPTY>
<!ATTLIST death
    xmlns CDATA #FIXED ''
    param CDATA #REQUIRED>

<!ELEMENT reproduction EMPTY>
<!ATTLIST reproduction
    xmlns CDATA #FIXED ''
    param CDATA #REQUIRED>

<!ELEMENT move EMPTY>
<!ATTLIST move
    xmlns CDATA #FIXED ''
    param CDATA #REQUIRED>

=== Jguer/IST-Discrete-Stochastic-Simulator/teste1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE simulation SYSTEM "simulation.dtd"> -->
<simulation finalinst="100" initpop="10" maxpop="50" comfortsens="3"> 
   <grid colsnb="5" rowsnb="4"/> 
   <initialpoint xinicial="1" yinicial="1"/>
   <finalpoint xfinal="5" yfinal="4"/>
   <specialcostzones>
      <zone xinicial="2" yinicial="2" xfinal="3" yfinal="3">4</zone>
      <zone xinicial="1" yinicial="1" xfinal="2" yfinal="4">6</zone>
      <zone xinicial="2" yinicial="2" xfinal="3" yfinal="3">12</zone>
   </specialcostzones>
   <obstacles num="4">
      <obstacle xpos="2" ypos="1"/>
      <obstacle xpos="2" ypos="3"/>
      <obstacle xpos="2" ypos="4"/>
      <obstacle xpos="4" ypos="2"/>
   </obstacles>
   <events>
      <death param="10"/>
      <reproduction param="1"/>
      <move param="1"/>
   </events>
</simulation>
